### ISSUE TITLE
رعایت نسبت یک به ده آپلود به دانلود

### ISSUE THREAD

**Issue by MAMSEIN** [radkesvat/WaterWall#118]
با سلام خدمت دوستان و مهندس عزیز بابت زحمات زیادی که میکشید برای بهتر شدن استفاده از اینترنت آزاد.

لطفا در صورت امکان قابلیت تنظیم رعایت نسبت دانلود به آپلود 1 به 10 را هم در این پروژه قرار دهید.
یا اگر راه جداگانه ای هست که میشه با این تونل ترکیب کرد و به مشکل نخورد معرفی کنید. به جز نامیزون و بعضی روش های دیگه که آپلود فیک انجام میده و سرور ایران شناسایی میکنه.

با تشکر از همگی

**Comment by radkesvat** [comment]
آپلود فیک tcp به سرور های ایران توی برنامه ام هست ؛ اگه پروژه ادامه پیدا کرد باید تا ماه بعد اوکی بشه...

**Comment by MAMSEIN** [comment]
> آپلود فیک tcp به سرور های ایران توی برنامه ام هست ؛ اگه پروژه ادامه پیدا کرد باید تا ماه بعد اوکی بشه...

انشالله که پروژه ادامه دار خواهد بود و آپلود فیک هم فعال میشه :)
لطفا فقط کاری کنید که بشه از وایرگارد هم استفاده کرد. من UdpListener رو میزنم حتی وصل هم میشه و وقتی با وایرگارد کانکت میشم تو سرور میزنه که وصل شده یه کانکشنی. اما خود وایرگارد یا OpenVPN کانکت نمیشه متاسفانه.

بازم ممنون

**Comment by radkesvat** [comment]
وقتی میخواید udp عبور بدید ؛ مثل همون تونل Tcp هست ولی باید یه نوع نود اضافه کنید که سایز پکت هارو نگه داره

باید مثلا protobuf رو استفاده کنید داخل زنجیره (برای انتقال udp از tcp که خوب میخواهید همینکارو بکنید به نظرم)

**Comment by netsupcloud** [comment]
> Owner

مهندس همچنان تانل ریورس grpc بدون cdn دقیقا سر 1 دقیقه کرش میکنه من که مجبورم تو داکر اجراش کنم خب خودش دوباره اجراش میکنه ولی کرش چرا میکنه ؟ خودتون تایمر تنظیم کردید ؟ version 1.28

**Comment by radkesvat** [comment]
کرش؟ ارورش چیه؟ من چند جا ران گذاشتم حتی یک بار هم ندیدم کرش کنه ... همین الان که پیام میدم سرور خودم از دیشب که نسخه اومد تا الان دست بهش نردم

**Comment by netsupcloud** [comment]
> کرش؟ ارورش چیه؟ من چند جا ران گذاشتم حتی یک بار هم ندیدم کرش کنه ... همین الان که پیام میدم سرور خودم از دیشب که نسخه اومد تا الان دست بهش نردم

هیچ اروری نمیده من داخل centos 8 stream نمیتونم ران کنمش ارور glibc_2.29 میده پس مجبورم تو داکر ubuntu 20 ران کنم و این باعث میشه هر 1 دقیقه دقیقا ریستارت کنه داکر ممکنه کرش نباشه کاملا وسط کار بدون ارور ریستارت میکنه به دلیل نامعلومی بسته میشه و اینم بگم من ریورس میزنم به 10 تا سرور ایران یعنی فایل core تعداد 10 تا کانفیک رو اجرا میکنه ولی وقتی 10 تا رو میکنم 1 سرور بازم همون اتفاق میوفته

**Comment by netsupcloud** [comment]
> کرش؟ ارورش چیه؟ من چند جا ران گذاشتم حتی یک بار هم ندیدم کرش کنه ... همین الان که پیام میدم سرور خودم از دیشب که نسخه اومد تا الان دست بهش نردم
root@srv ~]# docker logs wwc |grep error

2024-07-13 12:05:08.617 WARN  Http2Client: closing a session due to no ping reply
2024-07-13 12:05:08.817 WARN  Http2Client: closing a session due to no ping reply
2024-07-13 12:05:09.016 WARN  Http2Client: closing a session due to no ping reply
2024-07-13 12:05:09.116 WARN  Http2Client: closing a session due to no ping reply
2024-07-13 12:05:09.116 WARN  Http2Client: closing a session due to no ping reply
2024-07-13 12:05:09.117 WARN  Http2Client: closing a session due to no ping reply
2024-07-13 12:05:09.516 WARN  Http2Client: closing a session due to no ping reply
2024-07-13 12:05:09.516 WARN  Http2Client: closing a session due to no ping reply
2024-07-13 12:05:09.916 WARN  Http2Client: closing a session due to no ping reply
2024-07-13 12:05:10.316 WARN  Http2Client: closing a session due to no ping reply
2024-07-13 12:05:11.017 WARN  Http2Client: closing a session due to no ping reply
2024-07-13 12:05:11.117 WARN  Http2Client: closing a session due to no ping reply
2024-07-13 12:05:11.216 WARN  Http2Client: closing a session due to no ping reply
2024-07-13 12:05:20.003 WARN  connfd=2512 connect error: Transport endpoint is not connected:107
2024-07-13 12:05:23.011 WARN  connfd=3843 connect error: Transport endpoint is not connected:107
2024-07-13 12:05:23.075 WARN  connfd=4067 connect error: Transport endpoint is not connected:107

**Comment by netsupcloud** [comment]
> وقتی میخواید udp عبور بدید ؛ مثل همون تونل Tcp هست ولی باید یه نوع نود اضافه کنید که سایز پکت هارو نگه داره
> 
> باید مثلا protobuf رو استفاده کنید داخل زنجیره (برای انتقال udp از tcp که خوب میخواهید همینکارو بکنید به نظرم)
خب پس چرا ریورس جی ار پی سی رو که خودش پروتوباف داره رو تبدیل به udp میکنیم جواب نمیده؟

**Comment by netsupcloud** [comment]
> وقتی میخواید udp عبور بدید ؛ مثل همون تونل Tcp هست ولی باید یه نوع نود اضافه کنید که سایز پکت هارو نگه داره
> 
> باید مثلا protobuf رو استفاده کنید داخل زنجیره (برای انتقال udp از tcp که خوب میخواهید همینکارو بکنید به نظرم)




خب پس چرا ریورس جی ار پی سی رو که خودش پروتوباف داره رو تبدیل به udp میکنیم جواب نمیده؟

**Comment by radkesvat** [comment]
اینو تست نکردم ولی بر اساس تعوری باید کار کنه ؛ درمورد ارور glibc روی centos ؛ باید پروژه رو براش بیلد کنید که بیلد کردنش خیلی راحته من روی ابونتو با یک خط کد کل فرایند نصب و بیلد رو انجام میدم ولی برای سیستم عامل های دیگه باید یه چند خط دستور بیشتر باشه ؛ آموزش اش رو در داکیومنت ها خواهم نوشت

**Comment by MAMSEIN** [comment]
ممنون میشم ازتون اگر تونستید با وایرگارد متصل شید نمونه کانفیگ رو اینجا ارسال کنید چون من خیلی در این موارد و تنظیمات فایل کانفیگ اطلاعات ندارم که بدونم چجوری protobuf یا چیز دیگه اضافه کنم.
مرسی بازم

**Comment by netsupcloud** [comment]
> اینو تست نکردم ولی بر اساس تعوری باید کار کنه ؛ درمورد ارور glibc روی centos ؛ باید پروژه رو براش بیلد کنید که بیلد کردنش خیلی راحته من روی ابونتو با یک خط کد کل فرایند نصب و بیلد رو انجام میدم ولی برای سیستم عامل های دیگه باید یه چند خط دستور بیشتر باشه ؛ آموزش اش رو در داکیومنت ها خواهم نوشت



بسیار ممنون کامپایل کردم رو centos مشکل ریستارت سر 1 دقیقه هم با همون حل شد.

**Comment by radkesvat** [comment]
خودتون بیلد کردید ؟ نسخه release حتما بیلد کنید که پرفورمنس خوب بهتون بده، اگه فایل نهایی واتروال از ۸ مگابایت بیشتر شده سایزش یعنی نسخه debug هست و این اصلا پیشناهاد نمیشه. 
 اگه متوجه نشدید بگید بیشتر راهنمایی کنم
